// generated by genFromIdl.py
#include<w3c/svg/SVGMatrix.hpp>
#include<w3c/svg/SVGZoomEvent.hpp>
#include<w3c/svg/SVGAnimateMotionElement.hpp>
#include<w3c/svg/SVGFontFaceElement.hpp>
#include<w3c/svg/SVGFEFuncBElement.hpp>
#include<w3c/svg/SVGFEFuncAElement.hpp>
#include<w3c/svg/SVGFEFuncRElement.hpp>
#include<w3c/svg/SVGUnitTypes.hpp>
#include<w3c/svg/SVGForeignObjectElement.hpp>
#include<w3c/svg/SVGFEMorphologyElement.hpp>
#include<w3c/svg/SVGMarkerElement.hpp>
#include<w3c/svg/SVGFETileElement.hpp>
#include<w3c/svg/SVGPathElement.hpp>
#include<w3c/svg/SVGTSpanElement.hpp>
#include<w3c/svg/SVGRenderingIntent.hpp>
#include<w3c/svg/SVGMetadataElement.hpp>
#include<w3c/svg/SVGFEColorMatrixElement.hpp>
#include<w3c/svg/SVGRect.hpp>
#include<w3c/svg/SVGTRefElement.hpp>
#include<w3c/svg/SVGPathSeg.hpp>
#include<w3c/svg/SVGFEOffsetElement.hpp>
#include<w3c/svg/SVGSymbolElement.hpp>
#include<w3c/svg/SVGFEMergeNodeElement.hpp>
#include<w3c/svg/GetSVGDocument.hpp>
#include<w3c/svg/SVGColorProfileRule.hpp>
#include<w3c/svg/SVGStyleElement.hpp>
#include<w3c/svg/SVGPolygonElement.hpp>
#include<w3c/svg/SVGCursorElement.hpp>
#include<w3c/svg/SVGGlyphRefElement.hpp>
#include<w3c/svg/SVGGradientElement.hpp>
#include<w3c/svg/SVGFEImageElement.hpp>
#include<w3c/svg/SVGTextElement.hpp>
#include<w3c/svg/SVGFEPointLightElement.hpp>
#include<w3c/svg/SVGHKernElement.hpp>
#include<w3c/svg/SVGStopElement.hpp>
#include<w3c/svg/SVGRadialGradientElement.hpp>
#include<w3c/svg/SVGLineElement.hpp>
#include<w3c/svg/SVGFontFaceNameElement.hpp>
#include<w3c/svg/SVGPatternElement.hpp>
#include<w3c/svg/SVGCSSRule.hpp>
#include<w3c/svg/SVGScriptElement.hpp>
#include<w3c/svg/SVGLength.hpp>
#include<w3c/svg/SVGPaint.hpp>
#include<w3c/svg/SVGTextPathElement.hpp>
#include<w3c/svg/SVGFESpotLightElement.hpp>
#include<w3c/svg/SVGSVGElement.hpp>
#include<w3c/svg/SVGFECompositeElement.hpp>
#include<w3c/svg/SVGVKernElement.hpp>
#include<w3c/svg/SVGAElement.hpp>
#include<w3c/svg/SVGAltGlyphElement.hpp>
#include<w3c/svg/SVGColor.hpp>
#include<w3c/svg/SVGAnimateTransformElement.hpp>
#include<w3c/svg/SVGAngle.hpp>
#include<w3c/svg/SVGFEComponentTransferElement.hpp>
#include<w3c/svg/SVGFilterElement.hpp>
#include<w3c/svg/SVGFEBlendElement.hpp>
#include<w3c/svg/SVGFEMergeElement.hpp>
#include<w3c/svg/SVGTextPositioningElement.hpp>
#include<w3c/svg/SVGEllipseElement.hpp>
#include<w3c/svg/SVGClipPathElement.hpp>
#include<w3c/svg/SVGFontFaceUriElement.hpp>
#include<w3c/svg/SVGSwitchElement.hpp>
#include<w3c/svg/SVGMaskElement.hpp>
#include<w3c/svg/SVGViewElement.hpp>
#include<w3c/svg/SVGDefinitionSrcElement.hpp>
#include<w3c/svg/SVGFEDistantLightElement.hpp>
#include<w3c/svg/SVGFEDiffuseLightingElement.hpp>
#include<w3c/svg/SVGFontFaceSrcElement.hpp>
#include<w3c/svg/SVGDescElement.hpp>
#include<w3c/svg/SVGEvent.hpp>
#include<w3c/svg/SVGSetElement.hpp>
#include<w3c/svg/SVGPoint.hpp>
#include<w3c/svg/SVGAnimateElement.hpp>
#include<w3c/svg/SVGAnimationElement.hpp>
#include<w3c/svg/SVGAltGlyphDefElement.hpp>
#include<w3c/svg/SVGLinearGradientElement.hpp>
#include<w3c/svg/SVGFETurbulenceElement.hpp>
#include<w3c/svg/SVGComponentTransferFunctionElement.hpp>
#include<w3c/svg/SVGICCColor.hpp>
#include<w3c/svg/SVGLocatable.hpp>
#include<w3c/svg/SVGMPathElement.hpp>
#include<w3c/svg/SVGDefsElement.hpp>
#include<w3c/svg/SVGRectElement.hpp>
#include<w3c/svg/SVGPolylineElement.hpp>
#include<w3c/svg/SVGColorProfileElement.hpp>
#include<w3c/svg/SVGCircleElement.hpp>
#include<w3c/svg/SVGNumber.hpp>
#include<w3c/svg/SVGTextContentElement.hpp>
#include<w3c/svg/SVGUseElement.hpp>
#include<w3c/svg/SVGMissingGlyphElement.hpp>
#include<w3c/svg/SVGImageElement.hpp>
#include<w3c/svg/SVGElementInstance.hpp>
#include<w3c/svg/SVGFEFloodElement.hpp>
#include<w3c/svg/SVGFontElement.hpp>
#include<w3c/svg/SVGFEDisplacementMapElement.hpp>
#include<w3c/svg/SVGTitleElement.hpp>
#include<w3c/svg/SVGFEConvolveMatrixElement.hpp>
#include<w3c/svg/SVGFEGaussianBlurElement.hpp>
#include<w3c/svg/SVGGlyphElement.hpp>
#include<w3c/svg/SVGGElement.hpp>
#include<w3c/svg/SVGAnimateColorElement.hpp>
#include<w3c/svg/SVGFEFuncGElement.hpp>
#include<w3c/svg/SVGAltGlyphItemElement.hpp>
#include<w3c/svg/SVGFESpecularLightingElement.hpp>
#include<w3c/svg/SVGFontFaceFormatElement.hpp>

        namespace svg {
           SVGMatrix::~SVGMatrix() {}
   SVGZoomEvent::~SVGZoomEvent() {}
   SVGAnimateMotionElement::~SVGAnimateMotionElement() {}
   SVGFontFaceElement::~SVGFontFaceElement() {}
   SVGFEFuncBElement::~SVGFEFuncBElement() {}
   SVGFEFuncAElement::~SVGFEFuncAElement() {}
   SVGFEFuncRElement::~SVGFEFuncRElement() {}
   SVGUnitTypes::~SVGUnitTypes() {}
   SVGForeignObjectElement::~SVGForeignObjectElement() {}
   SVGFEMorphologyElement::~SVGFEMorphologyElement() {}
   SVGMarkerElement::~SVGMarkerElement() {}
   SVGFETileElement::~SVGFETileElement() {}
   SVGPathElement::~SVGPathElement() {}
   SVGTSpanElement::~SVGTSpanElement() {}
   SVGRenderingIntent::~SVGRenderingIntent() {}
   SVGMetadataElement::~SVGMetadataElement() {}
   SVGFEColorMatrixElement::~SVGFEColorMatrixElement() {}
   SVGRect::~SVGRect() {}
   SVGTRefElement::~SVGTRefElement() {}
   SVGPathSeg::~SVGPathSeg() {}
   SVGFEOffsetElement::~SVGFEOffsetElement() {}
   SVGSymbolElement::~SVGSymbolElement() {}
   SVGFEMergeNodeElement::~SVGFEMergeNodeElement() {}
   GetSVGDocument::~GetSVGDocument() {}
   SVGColorProfileRule::~SVGColorProfileRule() {}
   SVGStyleElement::~SVGStyleElement() {}
   SVGPolygonElement::~SVGPolygonElement() {}
   SVGCursorElement::~SVGCursorElement() {}
   SVGGlyphRefElement::~SVGGlyphRefElement() {}
   SVGGradientElement::~SVGGradientElement() {}
   SVGFEImageElement::~SVGFEImageElement() {}
   SVGTextElement::~SVGTextElement() {}
   SVGFEPointLightElement::~SVGFEPointLightElement() {}
   SVGHKernElement::~SVGHKernElement() {}
   SVGStopElement::~SVGStopElement() {}
   SVGRadialGradientElement::~SVGRadialGradientElement() {}
   SVGLineElement::~SVGLineElement() {}
   SVGFontFaceNameElement::~SVGFontFaceNameElement() {}
   SVGPatternElement::~SVGPatternElement() {}
   SVGCSSRule::~SVGCSSRule() {}
   SVGScriptElement::~SVGScriptElement() {}
   SVGLength::~SVGLength() {}
   SVGPaint::~SVGPaint() {}
   SVGTextPathElement::~SVGTextPathElement() {}
   SVGFESpotLightElement::~SVGFESpotLightElement() {}
   SVGSVGElement::~SVGSVGElement() {}
   SVGFECompositeElement::~SVGFECompositeElement() {}
   SVGVKernElement::~SVGVKernElement() {}
   SVGAElement::~SVGAElement() {}
   SVGAltGlyphElement::~SVGAltGlyphElement() {}
   SVGColor::~SVGColor() {}
   SVGAnimateTransformElement::~SVGAnimateTransformElement() {}
   SVGAngle::~SVGAngle() {}
   SVGFEComponentTransferElement::~SVGFEComponentTransferElement() {}
   SVGFilterElement::~SVGFilterElement() {}
   SVGFEBlendElement::~SVGFEBlendElement() {}
   SVGFEMergeElement::~SVGFEMergeElement() {}
   SVGTextPositioningElement::~SVGTextPositioningElement() {}
   SVGEllipseElement::~SVGEllipseElement() {}
   SVGClipPathElement::~SVGClipPathElement() {}
   SVGFontFaceUriElement::~SVGFontFaceUriElement() {}
   SVGSwitchElement::~SVGSwitchElement() {}
   SVGMaskElement::~SVGMaskElement() {}
   SVGViewElement::~SVGViewElement() {}
   SVGDefinitionSrcElement::~SVGDefinitionSrcElement() {}
   SVGFEDistantLightElement::~SVGFEDistantLightElement() {}
   SVGFEDiffuseLightingElement::~SVGFEDiffuseLightingElement() {}
   SVGFontFaceSrcElement::~SVGFontFaceSrcElement() {}
   SVGDescElement::~SVGDescElement() {}
   SVGEvent::~SVGEvent() {}
   SVGSetElement::~SVGSetElement() {}
   SVGPoint::~SVGPoint() {}
   SVGAnimateElement::~SVGAnimateElement() {}
   SVGAnimationElement::~SVGAnimationElement() {}
   SVGAltGlyphDefElement::~SVGAltGlyphDefElement() {}
   SVGLinearGradientElement::~SVGLinearGradientElement() {}
   SVGFETurbulenceElement::~SVGFETurbulenceElement() {}
   SVGComponentTransferFunctionElement::~SVGComponentTransferFunctionElement() {}
   SVGICCColor::~SVGICCColor() {}
   SVGLocatable::~SVGLocatable() {}
   SVGMPathElement::~SVGMPathElement() {}
   SVGDefsElement::~SVGDefsElement() {}
   SVGRectElement::~SVGRectElement() {}
   SVGPolylineElement::~SVGPolylineElement() {}
   SVGColorProfileElement::~SVGColorProfileElement() {}
   SVGCircleElement::~SVGCircleElement() {}
   SVGNumber::~SVGNumber() {}
   SVGTextContentElement::~SVGTextContentElement() {}
   SVGUseElement::~SVGUseElement() {}
   SVGMissingGlyphElement::~SVGMissingGlyphElement() {}
   SVGImageElement::~SVGImageElement() {}
   SVGElementInstance::~SVGElementInstance() {}
   SVGFEFloodElement::~SVGFEFloodElement() {}
   SVGFontElement::~SVGFontElement() {}
   SVGFEDisplacementMapElement::~SVGFEDisplacementMapElement() {}
   SVGTitleElement::~SVGTitleElement() {}
   SVGFEConvolveMatrixElement::~SVGFEConvolveMatrixElement() {}
   SVGFEGaussianBlurElement::~SVGFEGaussianBlurElement() {}
   SVGGlyphElement::~SVGGlyphElement() {}
   SVGGElement::~SVGGElement() {}
   SVGAnimateColorElement::~SVGAnimateColorElement() {}
   SVGFEFuncGElement::~SVGFEFuncGElement() {}
   SVGAltGlyphItemElement::~SVGAltGlyphItemElement() {}
   SVGFESpecularLightingElement::~SVGFESpecularLightingElement() {}
   SVGFontFaceFormatElement::~SVGFontFaceFormatElement() {}

        }
