// generated by makeParseAttribute.py

#include <svgl/xmlostream.hpp>
#include <svgl/printHelper.hpp>
#include <w3c/svg/makeEnumType.hpp>
#include <w3c/svg/String.hpp>
#include <w3c/svg/SVGAElement.hpp>
#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGURIReference.hpp>
#include <w3c/svg/SVGTests.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGTransformable.hpp>
#include <w3c/svg/SVGAltGlyphDefElement.hpp>
#include <w3c/svg/SVGAltGlyphElement.hpp>
#include <w3c/svg/SVGTextPositioningElement.hpp>
#include <w3c/svg/SVGTextContentElement.hpp>
#include <w3c/svg/SVGAltGlyphItemElement.hpp>
#include <w3c/svg/SVGAnimateColorElement.hpp>
#include <w3c/svg/SVGAnimationElement.hpp>
#include <w3c/svg/SVGAnimateElement.hpp>
#include <w3c/svg/SVGAnimateMotionElement.hpp>
#include <w3c/svg/SVGAnimateTransformElement.hpp>
#include <w3c/svg/SVGAnimatedPathData.hpp>
#include <w3c/svg/SVGAnimatedPoints.hpp>
#include <w3c/svg/SVGCircleElement.hpp>
#include <w3c/svg/SVGClipPathElement.hpp>
#include <w3c/svg/SVGColorProfileElement.hpp>
#include <w3c/svg/SVGComponentTransferFunctionElement.hpp>
#include <w3c/svg/SVGCursorElement.hpp>
#include <w3c/svg/SVGDefinitionSrcElement.hpp>
#include <w3c/svg/SVGDefsElement.hpp>
#include <w3c/svg/SVGDescElement.hpp>
#include <w3c/svg/SVGEllipseElement.hpp>
#include <w3c/svg/SVGFEBlendElement.hpp>
#include <w3c/svg/SVGFilterPrimitiveStandardAttributes.hpp>
#include <w3c/svg/SVGFEColorMatrixElement.hpp>
#include <w3c/svg/SVGFEComponentTransferElement.hpp>
#include <w3c/svg/SVGFECompositeElement.hpp>
#include <w3c/svg/SVGFEConvolveMatrixElement.hpp>
#include <w3c/svg/SVGFEDiffuseLightingElement.hpp>
#include <w3c/svg/SVGFEDisplacementMapElement.hpp>
#include <w3c/svg/SVGFEDistantLightElement.hpp>
#include <w3c/svg/SVGFEFloodElement.hpp>
#include <w3c/svg/SVGFEFuncAElement.hpp>
#include <w3c/svg/SVGFEFuncBElement.hpp>
#include <w3c/svg/SVGFEFuncGElement.hpp>
#include <w3c/svg/SVGFEFuncRElement.hpp>
#include <w3c/svg/SVGFEGaussianBlurElement.hpp>
#include <w3c/svg/SVGFEImageElement.hpp>
#include <w3c/svg/SVGFEMergeElement.hpp>
#include <w3c/svg/SVGFEMergeNodeElement.hpp>
#include <w3c/svg/SVGFEMorphologyElement.hpp>
#include <w3c/svg/SVGFEOffsetElement.hpp>
#include <w3c/svg/SVGFEPointLightElement.hpp>
#include <w3c/svg/SVGFESpecularLightingElement.hpp>
#include <w3c/svg/SVGFESpotLightElement.hpp>
#include <w3c/svg/SVGFETileElement.hpp>
#include <w3c/svg/SVGFETurbulenceElement.hpp>
#include <w3c/svg/SVGFilterElement.hpp>
#include <w3c/svg/SVGFitToViewBox.hpp>
#include <w3c/svg/SVGFontElement.hpp>
#include <w3c/svg/SVGFontFaceElement.hpp>
#include <w3c/svg/SVGFontFaceFormatElement.hpp>
#include <w3c/svg/SVGFontFaceNameElement.hpp>
#include <w3c/svg/SVGFontFaceSrcElement.hpp>
#include <w3c/svg/SVGFontFaceUriElement.hpp>
#include <w3c/svg/SVGForeignObjectElement.hpp>
#include <w3c/svg/SVGGElement.hpp>
#include <w3c/svg/SVGGlyphElement.hpp>
#include <w3c/svg/SVGGlyphRefElement.hpp>
#include <w3c/svg/SVGGradientElement.hpp>
#include <w3c/svg/SVGHKernElement.hpp>
#include <w3c/svg/SVGImageElement.hpp>
#include <w3c/svg/SVGLineElement.hpp>
#include <w3c/svg/SVGLinearGradientElement.hpp>
#include <w3c/svg/SVGMPathElement.hpp>
#include <w3c/svg/SVGMarkerElement.hpp>
#include <w3c/svg/SVGMaskElement.hpp>
#include <w3c/svg/SVGMetadataElement.hpp>
#include <w3c/svg/SVGMissingGlyphElement.hpp>
#include <w3c/svg/SVGPathElement.hpp>
#include <w3c/svg/SVGPatternElement.hpp>
#include <w3c/svg/SVGPolygonElement.hpp>
#include <w3c/svg/SVGPolylineElement.hpp>
#include <w3c/svg/SVGRadialGradientElement.hpp>
#include <w3c/svg/SVGRectElement.hpp>
#include <w3c/svg/SVGSVGElement.hpp>
#include <w3c/svg/SVGZoomAndPan.hpp>
#include <w3c/svg/SVGScriptElement.hpp>
#include <w3c/svg/SVGSetElement.hpp>
#include <w3c/svg/SVGStopElement.hpp>
#include <w3c/svg/SVGStyleElement.hpp>
#include <w3c/svg/SVGSwitchElement.hpp>
#include <w3c/svg/SVGSymbolElement.hpp>
#include <w3c/svg/SVGTRefElement.hpp>
#include <w3c/svg/SVGTSpanElement.hpp>
#include <w3c/svg/SVGTextElement.hpp>
#include <w3c/svg/SVGTextPathElement.hpp>
#include <w3c/svg/SVGTitleElement.hpp>
#include <w3c/svg/SVGUseElement.hpp>
#include <w3c/svg/SVGVKernElement.hpp>
#include <w3c/svg/SVGViewElement.hpp>
#include <w3c/svg/SVGViewSpec.hpp>


namespace svg {

// SVGAnimateMotionElement

void
SVGAnimateMotionElement::print_attributes(xmlostream& out)
{
   out << " values=\"" << values << "\"" << " path=\"" << path << "\"" << " rotate=\"" << rotate << "\""  ;
   SVGAnimationElement::print_attributes(out);
}

// SVGFontFaceUriElement

void
SVGFontFaceUriElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFontFaceElement

void
SVGFontFaceElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFEFuncBElement

void
SVGFEFuncBElement::print_attributes(xmlostream& out)
{
   SVGComponentTransferFunctionElement::print_attributes(out);
}

// SVGFEFuncAElement

void
SVGFEFuncAElement::print_attributes(xmlostream& out)
{
   SVGComponentTransferFunctionElement::print_attributes(out);
}

// SVGFEFuncRElement

void
SVGFEFuncRElement::print_attributes(xmlostream& out)
{
   SVGComponentTransferFunctionElement::print_attributes(out);
}

// SVGForeignObjectElement

void
SVGForeignObjectElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGFEMorphologyElement

void
SVGFEMorphologyElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " operator=\"" << operator_ << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGMarkerElement

void
SVGMarkerElement::print_attributes(xmlostream& out)
{
   out << " refX=\"" << refX << "\"" << " refY=\"" << refY << "\"" << " markerUnits=\"" << markerUnits << "\"" << " markerWidth=\"" << markerWidth << "\"" << " markerHeight=\"" << markerHeight << "\""  ;
   SVGElement::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
}

// SVGFETileElement

void
SVGFETileElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGPathElement

void
SVGPathElement::print_attributes(xmlostream& out)
{
   out << " pathLength=\"" << pathLength << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
   SVGAnimatedPathData::print_attributes(out);
}

// SVGTSpanElement

void
SVGTSpanElement::print_attributes(xmlostream& out)
{
   SVGTextPositioningElement::print_attributes(out);
}

// SVGFEColorMatrixElement

void
SVGFEColorMatrixElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " type=\"" << type << "\"" << " values=\"" << values << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGFontFaceFormatElement

void
SVGFontFaceFormatElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFEOffsetElement

void
SVGFEOffsetElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " dx=\"" << dx << "\"" << " dy=\"" << dy << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGSymbolElement

void
SVGSymbolElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
}

// SVGFEMergeNodeElement

void
SVGFEMergeNodeElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGTransformable

void
SVGTransformable::print_attributes(xmlostream& out)
{
   out << " transform=\"" << transform << "\""  ;
}

// SVGStyleElement

void
SVGStyleElement::print_attributes(xmlostream& out)
{
   out << " xml:space=\"" << xmlspace << "\"" << " type=\"" << type << "\"" << " media=\"" << media << "\"" << " title=\"" << title << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGPolygonElement

void
SVGPolygonElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
   SVGAnimatedPoints::print_attributes(out);
}

// SVGCursorElement

void
SVGCursorElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
}

// SVGFECompositeElement

void
SVGFECompositeElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " in2=\"" << in2 << "\"" << " operator=\"" << operator_ << "\"" << " k1=\"" << k1 << "\"" << " k2=\"" << k2 << "\"" << " k3=\"" << k3 << "\"" << " k4=\"" << k4 << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGGradientElement

void
SVGGradientElement::print_attributes(xmlostream& out)
{
   out << " gradientUnits=\"" << gradientUnits << "\"" << " gradientTransform=\"" << gradientTransform << "\"" << " spreadMethod=\"" << spreadMethod << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGLinearGradientElement

void
SVGLinearGradientElement::print_attributes(xmlostream& out)
{
   out << " x1=\"" << x1 << "\"" << " y1=\"" << y1 << "\"" << " x2=\"" << x2 << "\"" << " y2=\"" << y2 << "\""  ;
   SVGGradientElement::print_attributes(out);
}

// SVGTextElement

void
SVGTextElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\""  ;
   SVGTextContentElement::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGFEPointLightElement

void
SVGFEPointLightElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " z=\"" << z << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGHKernElement

void
SVGHKernElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGStopElement

void
SVGStopElement::print_attributes(xmlostream& out)
{
   out << " offset=\"" << offset << "\""  ;
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGFEDisplacementMapElement

void
SVGFEDisplacementMapElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " in2=\"" << in2 << "\"" << " scale=\"" << scale << "\"" << " xChannelSelector=\"" << xChannelSelector << "\"" << " yChannelSelector=\"" << yChannelSelector << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGLineElement

void
SVGLineElement::print_attributes(xmlostream& out)
{
   out << " x1=\"" << x1 << "\"" << " y1=\"" << y1 << "\"" << " x2=\"" << x2 << "\"" << " y2=\"" << y2 << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGFontFaceNameElement

void
SVGFontFaceNameElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGPatternElement

void
SVGPatternElement::print_attributes(xmlostream& out)
{
   out << " patternUnits=\"" << patternUnits << "\"" << " patternTransform=\"" << patternTransform << "\"" << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
}

// SVGExternalResourcesRequired

void
SVGExternalResourcesRequired::print_attributes(xmlostream& out)
{
   out << " externalResourcesRequired=\"" << externalResourcesRequired << "\""  ;
}

// SVGScriptElement

void
SVGScriptElement::print_attributes(xmlostream& out)
{
   out << " type=\"" << type << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
}

// SVGStylable

void
SVGStylable::print_attributes(xmlostream& out)
{
   out << " class=\"" << className << "\"" << " style=\"" << style << "\""  ;
}

// SVGFitToViewBox

void
SVGFitToViewBox::print_attributes(xmlostream& out)
{
   out << " viewBox=\"" << viewBox << "\"" << " preserveAspectRatio=\"" << preserveAspectRatio << "\""  ;
}

// SVGTests

void
SVGTests::print_attributes(xmlostream& out)
{
   out << " requiredFeatures=\"" << requiredFeatures << "\"" << " requiredExtensions=\"" << requiredExtensions << "\"" << " systemLanguage=\"" << systemLanguage << "\""  ;
}

// SVGSVGElement

void
SVGSVGElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\"" << " contentScriptType=\"" << contentScriptType << "\"" << " contentStyleType=\"" << contentStyleType << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
   SVGZoomAndPan::print_attributes(out);
}

// SVGViewSpec

void
SVGViewSpec::print_attributes(xmlostream& out)
{
   SVGZoomAndPan::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
}

// SVGVKernElement

void
SVGVKernElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGMetadataElement

void
SVGMetadataElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGAElement

void
SVGAElement::print_attributes(xmlostream& out)
{
   out << " target=\"" << target << "\"" << " xlink:show=\"" << xlinkShow << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGAltGlyphElement

void
SVGAltGlyphElement::print_attributes(xmlostream& out)
{
   out << " glyphRef=\"" << glyphRef << "\"" << " format=\"" << format << "\""  ;
   SVGTextPositioningElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
}

// SVGURIReference

void
SVGURIReference::print_attributes(xmlostream& out)
{
   out << " xlink:type=\"" << xlinkType << "\"" << " xlink:role=\"" << xlinkRole << "\"" << " xlink:arcrole=\"" << xlinkArcRole << "\"" << " xlink:title=\"" << xlinkTitle << "\"" << " xlink:show=\"" << xlinkShow << "\"" << " xlink:actuate=\"" << xlinkActuate << "\"" << " xlink:href=\"" << href << "\""  ;
}

// SVGAnimateTransformElement

void
SVGAnimateTransformElement::print_attributes(xmlostream& out)
{
   out << " values=\"" << values << "\"" << " type=\"" << type << "\""  ;
   SVGAnimationElement::print_attributes(out);
}

// SVGFEComponentTransferElement

void
SVGFEComponentTransferElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGFEBlendElement

void
SVGFEBlendElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " in2=\"" << in2 << "\"" << " mode=\"" << mode << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGFEMergeElement

void
SVGFEMergeElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGTextPositioningElement

void
SVGTextPositioningElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " dx=\"" << dx << "\"" << " dy=\"" << dy << "\"" << " rotate=\"" << rotate << "\""  ;
   SVGTextContentElement::print_attributes(out);
}

// SVGEllipseElement

void
SVGEllipseElement::print_attributes(xmlostream& out)
{
   out << " cx=\"" << cx << "\"" << " cy=\"" << cy << "\"" << " rx=\"" << rx << "\"" << " ry=\"" << ry << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGFilterElement

void
SVGFilterElement::print_attributes(xmlostream& out)
{
   out << " filterUnits=\"" << filterUnits << "\"" << " primitiveUnits=\"" << primitiveUnits << "\"" << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGClipPathElement

void
SVGClipPathElement::print_attributes(xmlostream& out)
{
   out << " clipPathUnits=\"" << clipPathUnits << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGSwitchElement

void
SVGSwitchElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGMaskElement

void
SVGMaskElement::print_attributes(xmlostream& out)
{
   out << " maskUnits=\"" << maskUnits << "\"" << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGViewElement

void
SVGViewElement::print_attributes(xmlostream& out)
{
   out << " viewTarget=\"" << viewTarget << "\""  ;
   SVGElement::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGFitToViewBox::print_attributes(out);
   SVGZoomAndPan::print_attributes(out);
}

// SVGDefinitionSrcElement

void
SVGDefinitionSrcElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFilterPrimitiveStandardAttributes

void
SVGFilterPrimitiveStandardAttributes::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\"" << " result=\"" << result << "\""  ;
}

// SVGFEDistantLightElement

void
SVGFEDistantLightElement::print_attributes(xmlostream& out)
{
   out << " azimuth=\"" << azimuth << "\"" << " elevation=\"" << elevation << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGFEDiffuseLightingElement

void
SVGFEDiffuseLightingElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " surfaceScale=\"" << surfaceScale << "\"" << " diffuseConstant=\"" << diffuseConstant << "\""  ;
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGAnimatedPathData

void
SVGAnimatedPathData::print_attributes(xmlostream& out)
{
   out << " d=\"" << pathSegList << "\""  ;
}

// SVGFontFaceSrcElement

void
SVGFontFaceSrcElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGZoomAndPan

void
SVGZoomAndPan::print_attributes(xmlostream& out)
{
   out << " zoomAndPan=\"" << zoomAndPan << "\""  ;
}

// SVGDescElement

void
SVGDescElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGSetElement

void
SVGSetElement::print_attributes(xmlostream& out)
{
   SVGAnimationElement::print_attributes(out);
}

// SVGAnimateElement

void
SVGAnimateElement::print_attributes(xmlostream& out)
{
   out << " values=\"" << values << "\""  ;
   SVGAnimationElement::print_attributes(out);
}

// SVGLangSpace

void
SVGLangSpace::print_attributes(xmlostream& out)
{
   out << " xml:lang=\"" << xmllang << "\"" << " xml:space=\"" << xmlspace << "\""  ;
}

// SVGGlyphRefElement

void
SVGGlyphRefElement::print_attributes(xmlostream& out)
{
   out << " glyphRef=\"" << glyphRef << "\"" << " format=\"" << format << "\"" << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " dx=\"" << dx << "\"" << " dy=\"" << dy << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGFESpotLightElement

void
SVGFESpotLightElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " z=\"" << z << "\"" << " pointsAtX=\"" << pointsAtX << "\"" << " pointsAtY=\"" << pointsAtY << "\"" << " pointsAtZ=\"" << pointsAtZ << "\"" << " specularExponent=\"" << specularExponent << "\"" << " limitingConeAngle=\"" << limitingConeAngle << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGAnimationElement

void
SVGAnimationElement::print_attributes(xmlostream& out)
{
   out << " attributeName=\"" << attributeName << "\"" << " attributeType=\"" << attributeType << "\"" << " begin=\"" << begin << "\"" << " dur=\"" << dur << "\"" << " end=\"" << end << "\"" << " min=\"" << min << "\"" << " max=\"" << max << "\"" << " restart=\"" << restart << "\"" << " repeatCount=\"" << repeatCount << "\"" << " repeatDur=\"" << repeatDur << "\"" << " fill=\"" << fill << "\"" << " from=\"" << from << "\"" << " to=\"" << to << "\"" << " by=\"" << by << "\"" << " keyTimes=\"" << keyTimes << "\"" << " keySplines=\"" << keySplines << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
}

// SVGAltGlyphDefElement

void
SVGAltGlyphDefElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFETurbulenceElement

void
SVGFETurbulenceElement::print_attributes(xmlostream& out)
{
   out << " numOctaves=\"" << numOctaves << "\"" << " seed=\"" << seed << "\"" << " stitchTiles=\"" << stitchTiles << "\"" << " type=\"" << type << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGComponentTransferFunctionElement

void
SVGComponentTransferFunctionElement::print_attributes(xmlostream& out)
{
   out << " type=\"" << type << "\"" << " tableValues=\"" << tableValues << "\"" << " slope=\"" << slope << "\"" << " intercept=\"" << intercept << "\"" << " amplitude=\"" << amplitude << "\"" << " exponent=\"" << exponent << "\"" << " offset=\"" << offset << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGMPathElement

void
SVGMPathElement::print_attributes(xmlostream& out)
{
   out << " xlink:href=\"" << href << "\""  ;
   SVGElement::print_attributes(out);
}

// SVGDefsElement

void
SVGDefsElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGRectElement

void
SVGRectElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\"" << " rx=\"" << rx << "\"" << " ry=\"" << ry << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGPolylineElement

void
SVGPolylineElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
   SVGAnimatedPoints::print_attributes(out);
}

// SVGColorProfileElement

void
SVGColorProfileElement::print_attributes(xmlostream& out)
{
   out << " local=\"" << local << "\"" << " name=\"" << name << "\"" << " rendering-intent=\"" << renderingIntent << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
}

// SVGAnimatedPoints

void
SVGAnimatedPoints::print_attributes(xmlostream& out)
{
   out << " points=\"" << points << "\""  ;
}

// SVGCircleElement

void
SVGCircleElement::print_attributes(xmlostream& out)
{
   out << " cx=\"" << cx << "\"" << " cy=\"" << cy << "\"" << " r=\"" << r << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGTextContentElement

void
SVGTextContentElement::print_attributes(xmlostream& out)
{
   out << " textLength=\"" << textLength << "\"" << " lengthAdjust=\"" << lengthAdjust << "\""  ;
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGUseElement

void
SVGUseElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGMissingGlyphElement

void
SVGMissingGlyphElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGImageElement

void
SVGImageElement::print_attributes(xmlostream& out)
{
   out << " x=\"" << x << "\"" << " y=\"" << y << "\"" << " width=\"" << width << "\"" << " height=\"" << height << "\"" << " preserveAspectRatio=\"" << preserveAspectRatio << "\""  ;
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGFEImageElement

void
SVGFEImageElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGTextPathElement

void
SVGTextPathElement::print_attributes(xmlostream& out)
{
   out << " startOffset=\"" << startOffset << "\"" << " method=\"" << method << "\"" << " spacing=\"" << spacing << "\""  ;
   SVGTextContentElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
}

// SVGFEFloodElement

void
SVGFEFloodElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " flood-color=\"" << floodColor << "\"" << " flood-opacity=\"" << floodOpacity << "\""  ;
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGFontElement

void
SVGFontElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGRadialGradientElement

void
SVGRadialGradientElement::print_attributes(xmlostream& out)
{
   out << " cx=\"" << cx << "\"" << " cy=\"" << cy << "\"" << " r=\"" << r << "\"" << " fx=\"" << fx << "\"" << " fy=\"" << fy << "\""  ;
   SVGGradientElement::print_attributes(out);
}

// SVGElement

void
SVGElement::print_attributes(xmlostream& out)
{
   out << " id=\"" << id << "\""  ;
}

// SVGTitleElement

void
SVGTitleElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGFEConvolveMatrixElement

void
SVGFEConvolveMatrixElement::print_attributes(xmlostream& out)
{
   out << " kernelMatrix=\"" << kernelMatrix << "\"" << " divisor=\"" << divisor << "\"" << " bias=\"" << bias << "\"" << " targetX=\"" << targetX << "\"" << " targetY=\"" << targetY << "\"" << " edgeMode=\"" << edgeMode << "\"" << " preserveAlpha=\"" << preserveAlpha << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGFEGaussianBlurElement

void
SVGFEGaussianBlurElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\""  ;
   SVGElement::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGGlyphElement

void
SVGGlyphElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
}

// SVGGElement

void
SVGGElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
   SVGTests::print_attributes(out);
   SVGLangSpace::print_attributes(out);
   SVGExternalResourcesRequired::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGTransformable::print_attributes(out);
}

// SVGAnimateColorElement

void
SVGAnimateColorElement::print_attributes(xmlostream& out)
{
   out << " values=\"" << values << "\""  ;
   SVGAnimationElement::print_attributes(out);
}

// SVGFEFuncGElement

void
SVGFEFuncGElement::print_attributes(xmlostream& out)
{
   SVGComponentTransferFunctionElement::print_attributes(out);
}

// SVGAltGlyphItemElement

void
SVGAltGlyphItemElement::print_attributes(xmlostream& out)
{
   SVGElement::print_attributes(out);
}

// SVGFESpecularLightingElement

void
SVGFESpecularLightingElement::print_attributes(xmlostream& out)
{
   out << " in=\"" << in1 << "\"" << " surfaceScale=\"" << surfaceScale << "\"" << " specularConstant=\"" << specularConstant << "\"" << " specularExponent=\"" << specularExponent << "\""  ;
   SVGElement::print_attributes(out);
   SVGStylable::print_attributes(out);
   SVGFilterPrimitiveStandardAttributes::print_attributes(out);
}

// SVGTRefElement

void
SVGTRefElement::print_attributes(xmlostream& out)
{
   SVGTextPositioningElement::print_attributes(out);
   SVGURIReference::print_attributes(out);
}

}
