// generated by makeAnimated.py
#ifndef __svg_AnimatedPreserveAspectRatio__
#define __svg_AnimatedPreserveAspectRatio__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGPreserveAspectRatio.hpp>

namespace svg {
   typedef Animated<SVGPreserveAspectRatio> SVGAnimatedPreserveAspectRatio;
}

#endif // __svg_AnimatedPreserveAspectRatio__
