// generated by makeAnimated.py
#ifndef __svg_AnimatedInteger__
#define __svg_AnimatedInteger__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGInteger.hpp>

namespace svg {
   typedef Animated<SVGInteger> SVGAnimatedInteger;
}

#endif // __svg_AnimatedInteger__
