// generated by makeAnimated.py
#ifndef __svg_AnimatedAngle__
#define __svg_AnimatedAngle__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGAngle.hpp>

namespace svg {
   typedef Animated<SVGAngle> SVGAnimatedAngle;
}

#endif // __svg_AnimatedAngle__
