#ifndef __svg_SVGAngle__
#define __svg_SVGAngle__

// generated by genFromIdl.py

namespace svg {
}

#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/DOMString.hpp>

namespace svg {
	class SVGAngle {
	public:

		enum SVG_ANGLETYPE {
			SVG_ANGLETYPE_UNKNOWN = 0,
			SVG_ANGLETYPE_UNSPECIFIED = 1,
			SVG_ANGLETYPE_DEG = 2,
			SVG_ANGLETYPE_RAD = 3,
			SVG_ANGLETYPE_GRAD = 4
		};

	protected:
		Attribute< SVG_ANGLETYPE > unitType;
		Attribute< float > value;
		Attribute< float > valueInSpecifiedUnits;
		Attribute< DOMString > valueAsString;
	public:
		const Attribute< SVG_ANGLETYPE >& dom_getUnitType() const { return unitType; }

		const Attribute< float >& dom_getValue() const { return value; }
		Attribute< float >& dom_getValue() { return value; }
		void dom_setValue(const float& n)  { value.setValue(n); }

		const Attribute< float >& dom_getValueInSpecifiedUnits() const { return valueInSpecifiedUnits; }
		Attribute< float >& dom_getValueInSpecifiedUnits() { return valueInSpecifiedUnits; }
		void dom_setValueInSpecifiedUnits(const float& n)  { valueInSpecifiedUnits.setValue(n); }

		const Attribute< DOMString >& dom_getValueAsString() const { return valueAsString; }
		Attribute< DOMString >& dom_getValueAsString() { return valueAsString; }
		void dom_setValueAsString(const DOMString& n)  ;

	public:
		const SVG_ANGLETYPE & getUnitType() const { return unitType.getValue(); }
		void setUnitType(const SVG_ANGLETYPE& n)  { unitType.setValue(n); }

		const float & getValue() const { return value.getValue(); }
		float & getValue() { return value.getValue(); }
		void setValue(const float& n)  { value.setValue(n); }

		const float & getValueInSpecifiedUnits() const { return valueInSpecifiedUnits.getValue(); }
		float & getValueInSpecifiedUnits() { return valueInSpecifiedUnits.getValue(); }
		void setValueInSpecifiedUnits(const float& n)  { valueInSpecifiedUnits.setValue(n); }

		const DOMString & getValueAsString() const { return valueAsString.getValue(); }
		DOMString & getValueAsString() { return valueAsString.getValue(); }
		void setValueAsString(const DOMString& n)  ;

	public:
		virtual void newValueSpecifiedUnits ( unsigned short unitType, float valueInSpecifiedUnits ) ;
		virtual void convertToSpecifiedUnits ( unsigned short unitType ) ;

	public:
		virtual ~SVGAngle();
	};
}


#endif // __svg_SVGAngle__
