// generated by makeAnimated.py
#ifndef __svg_AnimatedRect__
#define __svg_AnimatedRect__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGRect.hpp>

namespace svg {
   typedef Animated<SVGRect> SVGAnimatedRect;
}

#endif // __svg_AnimatedRect__
