// generated by makeAnimated.py
#ifndef __svg_AnimatedEnumeration__
#define __svg_AnimatedEnumeration__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGEnumeration.hpp>

namespace svg {
   typedef Animated<SVGEnumeration> SVGAnimatedEnumeration;
}

#endif // __svg_AnimatedEnumeration__
