// generated by makeAnimated.py
#ifndef __svg_AnimatedLength__
#define __svg_AnimatedLength__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGLength.hpp>

namespace svg {
   typedef Animated<SVGLength> SVGAnimatedLength;
}

#endif // __svg_AnimatedLength__
