// generated by makeAnimated.py
#ifndef __svg_AnimatedBoolean__
#define __svg_AnimatedBoolean__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGBoolean.hpp>

namespace svg {
   typedef Animated<SVGBoolean> SVGAnimatedBoolean;
}

#endif // __svg_AnimatedBoolean__
