// generated by makeAnimated.py
#ifndef __svg_AnimatedNumber__
#define __svg_AnimatedNumber__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGNumber.hpp>

namespace svg {
   typedef Animated<SVGNumber> SVGAnimatedNumber;
}

#endif // __svg_AnimatedNumber__
