// generated by makeAnimated.py
#ifndef __svg_AnimatedTransformList__
#define __svg_AnimatedTransformList__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGTransformList.hpp>

namespace svg {
   typedef Animated<SVGTransformList> SVGAnimatedTransformList;
}

#endif // __svg_AnimatedTransformList__
