#ifndef __svg_SVGAnimatedPoints__
#define __svg_SVGAnimatedPoints__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGPointList.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
	class SVGAnimatedPoints {
	public:
	protected:
		Attribute< SVGPointList > points;
		Attribute< SVGPointList > animatedPoints;
	public:
		const Attribute< SVGPointList >& dom_getPoints() const { return points; }

		const Attribute< SVGPointList >& dom_getAnimatedPoints() const { return animatedPoints; }

	public:
		const SVGPointList & getPoints() const { return points.getValue(); }
		void setPoints(const SVGPointList& n)  { points.setValue(n); }

		const SVGPointList & getAnimatedPoints() const { return animatedPoints.getValue(); }
		void setAnimatedPoints(const SVGPointList& n)  { animatedPoints.setValue(n); }


	public:
		virtual ~SVGAnimatedPoints() {}
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);
	};
}


#endif // __svg_SVGAnimatedPoints__
