// generated by makeAnimated.py
#ifndef __svg_AnimatedLengthList__
#define __svg_AnimatedLengthList__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGLengthList.hpp>

namespace svg {
   typedef Animated<SVGLengthList> SVGAnimatedLengthList;
}

#endif // __svg_AnimatedLengthList__
