// generated by makeAnimated.py
#ifndef __svg_AnimatedString__
#define __svg_AnimatedString__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGString.hpp>

namespace svg {
   typedef Animated<SVGString> SVGAnimatedString;
}

#endif // __svg_AnimatedString__
