// generated by makeAnimated.py
#ifndef __svg_AnimatedNumberList__
#define __svg_AnimatedNumberList__

#include <w3c/svg/Animated.hpp>
#include <w3c/svg/SVGNumberList.hpp>

namespace svg {
   typedef Animated<SVGNumberList> SVGAnimatedNumberList;
}

#endif // __svg_AnimatedNumberList__
