#ifndef __svg_SVGCSSRule__
#define __svg_SVGCSSRule__

// generated by genFromIdl.py

namespace svg {
}

#include <w3c/css/CSSRule.hpp>

namespace svg {
	class SVGCSSRule :
		public css::CSSRule {
	public:
	public:

	public:
		virtual ~SVGCSSRule();
	};
}


#endif // __svg_SVGCSSRule__
