#ifndef __svg_SVGDefinitionSrcElement__
#define __svg_SVGDefinitionSrcElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGDefinitionSrcElement_element_string;
}

namespace svg {
	class SVGDefinitionSrcElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGDefinitionSrcElement();
		virtual const String getDtdElement() const { return SVGDefinitionSrcElement_element_string; }
		SVGDefinitionSrcElement(dom::Document* doc) : SVGElement(doc, SVGDefinitionSrcElement_element_string) {}
	};
}


#endif // __svg_SVGDefinitionSrcElement__
