#ifndef __svg_SVGExternalResourcesRequired__
#define __svg_SVGExternalResourcesRequired__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGAnimatedBoolean.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
	class SVGExternalResourcesRequired {
	public:
	protected:
		Attribute< SVGAnimatedBoolean > externalResourcesRequired;
	public:
		const Attribute< SVGAnimatedBoolean >& dom_getExternalResourcesRequired() const { return externalResourcesRequired; }

	public:
		const SVGBoolean & getExternalResourcesRequired() const { return externalResourcesRequired.getValue().getAnimatedVal().getValue(); }
		void setExternalResourcesRequired(const SVGBoolean& n)  { externalResourcesRequired.getValue().getAnimatedVal().setValue(n); externalResourcesRequired.getValue().getBaseVal().setValue(n); }


	public:
		virtual ~SVGExternalResourcesRequired() {}
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);
	};
}


#endif // __svg_SVGExternalResourcesRequired__
