// generated by makeList.py
#ifndef __svg_ElementInstanceList__
#define __svg_ElementInstanceList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGElementInstance.hpp>

namespace svg {
   typedef SVGList<SVGElementInstance> SVGElementInstanceList;
}

#endif // __svg_ElementInstanceList__
