#ifndef __svg_SVGEvent__
#define __svg_SVGEvent__

// generated by genFromIdl.py

namespace svg {
}

#include <w3c/events/Event.hpp>

namespace svg {
	class SVGEvent :
		public events::Event {
	public:
	public:

	public:
		virtual ~SVGEvent();
	};
}


#endif // __svg_SVGEvent__
