#ifndef __svg_SVGFontFaceFormatElement__
#define __svg_SVGFontFaceFormatElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFontFaceFormatElement_element_string;
}

namespace svg {
	class SVGFontFaceFormatElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFontFaceFormatElement();
		virtual const String getDtdElement() const { return SVGFontFaceFormatElement_element_string; }
		SVGFontFaceFormatElement(dom::Document* doc) : SVGElement(doc, SVGFontFaceFormatElement_element_string) {}
	};
}


#endif // __svg_SVGFontFaceFormatElement__
