#ifndef __svg_SVGFEFuncAElement__
#define __svg_SVGFEFuncAElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGComponentTransferFunctionElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFEFuncAElement_element_string;
}

namespace svg {
	class SVGFEFuncAElement :
		public SVGComponentTransferFunctionElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFEFuncAElement();
		virtual const String getDtdElement() const { return SVGFEFuncAElement_element_string; }
		SVGFEFuncAElement(dom::Document* doc) : SVGComponentTransferFunctionElement(doc, SVGFEFuncAElement_element_string) {}
	};
}


#endif // __svg_SVGFEFuncAElement__
