#ifndef __svg_SVGFEPointLightElement__
#define __svg_SVGFEPointLightElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGAnimatedNumber.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFEPointLightElement_element_string;
}

namespace svg {
	class SVGFEPointLightElement :
		public SVGElement {
	public:
	protected:
		Attribute< SVGAnimatedNumber > x;
		Attribute< SVGAnimatedNumber > y;
		Attribute< SVGAnimatedNumber > z;
	public:
		const Attribute< SVGAnimatedNumber >& dom_getX() const { return x; }

		const Attribute< SVGAnimatedNumber >& dom_getY() const { return y; }

		const Attribute< SVGAnimatedNumber >& dom_getZ() const { return z; }

	public:
		const SVGNumber & getX() const { return x.getValue().getAnimatedVal().getValue(); }
		void setX(const SVGNumber& n)  { x.getValue().getAnimatedVal().setValue(n); x.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getY() const { return y.getValue().getAnimatedVal().getValue(); }
		void setY(const SVGNumber& n)  { y.getValue().getAnimatedVal().setValue(n); y.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getZ() const { return z.getValue().getAnimatedVal().getValue(); }
		void setZ(const SVGNumber& n)  { z.getValue().getAnimatedVal().setValue(n); z.getValue().getBaseVal().setValue(n);  setDamaged(true); }

	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFEPointLightElement();
		virtual const String getDtdElement() const { return SVGFEPointLightElement_element_string; }
		SVGFEPointLightElement(dom::Document* doc) : SVGElement(doc, SVGFEPointLightElement_element_string) {}
	};
}


#endif // __svg_SVGFEPointLightElement__
