#ifndef __svg_SVGFESpecularLightingElement__
#define __svg_SVGFESpecularLightingElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
	class SVGElement;
}

namespace svgl {
	class AnimateAdapter;
	class Context;
	class GLInfo;
	class FilterContext;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGFilterPrimitiveStandardAttributes.hpp>
#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGAnimatedString.hpp>
#include <w3c/svg/SVGAnimatedNumber.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFESpecularLightingElement_element_string;
}

namespace svg {
	class SVGFESpecularLightingElement :
		public SVGElement,
		public SVGStylable,
		public SVGFilterPrimitiveStandardAttributes {
	public:
	protected:
		Attribute< SVGAnimatedString > in1;
		Attribute< SVGAnimatedNumber > surfaceScale;
		Attribute< SVGAnimatedNumber > specularConstant;
		Attribute< SVGAnimatedNumber > specularExponent;
	public:
		const Attribute< SVGAnimatedString >& dom_getIn1() const { return in1; }

		const Attribute< SVGAnimatedNumber >& dom_getSurfaceScale() const { return surfaceScale; }

		const Attribute< SVGAnimatedNumber >& dom_getSpecularConstant() const { return specularConstant; }

		const Attribute< SVGAnimatedNumber >& dom_getSpecularExponent() const { return specularExponent; }

	public:
		const SVGString & getIn1() const { return in1.getValue().getAnimatedVal().getValue(); }
		void setIn1(const SVGString& n)  { in1.getValue().getAnimatedVal().setValue(n); in1.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getSurfaceScale() const { return surfaceScale.getValue().getAnimatedVal().getValue(); }
		void setSurfaceScale(const SVGNumber& n)  { surfaceScale.getValue().getAnimatedVal().setValue(n); surfaceScale.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getSpecularConstant() const { return specularConstant.getValue().getAnimatedVal().getValue(); }
		void setSpecularConstant(const SVGNumber& n)  { specularConstant.getValue().getAnimatedVal().setValue(n); specularConstant.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getSpecularExponent() const { return specularExponent.getValue().getAnimatedVal().getValue(); }
		void setSpecularExponent(const SVGNumber& n)  { specularExponent.getValue().getAnimatedVal().setValue(n); specularExponent.getValue().getBaseVal().setValue(n);  setDamaged(true); }


		virtual void glPreTraverse(svgl::Context*, svgl::GLInfo*, SVGElement* elem, svgl::FilterContext*)  ;
		virtual void glPostTraverse(svgl::Context*, svgl::GLInfo*, SVGElement* elem, svgl::FilterContext*)  ;
		virtual unicode::String* getOptionalIn1();
		virtual unicode::String* getOptionalIn2();
		virtual unicode::String* getOptionalResult();

	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFESpecularLightingElement();
		virtual const String getDtdElement() const { return SVGFESpecularLightingElement_element_string; }
		SVGFESpecularLightingElement(dom::Document* doc) : SVGElement(doc, SVGFESpecularLightingElement_element_string) {}
	};
}


#endif // __svg_SVGFESpecularLightingElement__
