#ifndef __svg_SVGFEFuncBElement__
#define __svg_SVGFEFuncBElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGComponentTransferFunctionElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFEFuncBElement_element_string;
}

namespace svg {
	class SVGFEFuncBElement :
		public SVGComponentTransferFunctionElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFEFuncBElement();
		virtual const String getDtdElement() const { return SVGFEFuncBElement_element_string; }
		SVGFEFuncBElement(dom::Document* doc) : SVGComponentTransferFunctionElement(doc, SVGFEFuncBElement_element_string) {}
	};
}


#endif // __svg_SVGFEFuncBElement__
