#ifndef __svg_SVGFontFaceUriElement__
#define __svg_SVGFontFaceUriElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFontFaceUriElement_element_string;
}

namespace svg {
	class SVGFontFaceUriElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFontFaceUriElement();
		virtual const String getDtdElement() const { return SVGFontFaceUriElement_element_string; }
		SVGFontFaceUriElement(dom::Document* doc) : SVGElement(doc, SVGFontFaceUriElement_element_string) {}
	};
}


#endif // __svg_SVGFontFaceUriElement__
