#ifndef __svg_SVGFontFaceSrcElement__
#define __svg_SVGFontFaceSrcElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFontFaceSrcElement_element_string;
}

namespace svg {
	class SVGFontFaceSrcElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFontFaceSrcElement();
		virtual const String getDtdElement() const { return SVGFontFaceSrcElement_element_string; }
		SVGFontFaceSrcElement(dom::Document* doc) : SVGElement(doc, SVGFontFaceSrcElement_element_string) {}
	};
}


#endif // __svg_SVGFontFaceSrcElement__
