#ifndef __svg_SVGFEFloodElement__
#define __svg_SVGFEFloodElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
	class SVGElement;
}

namespace svgl {
	class AnimateAdapter;
	class Context;
	class GLInfo;
	class FilterContext;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGFilterPrimitiveStandardAttributes.hpp>
#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGAnimatedString.hpp>
#include <w3c/svg/SVGAnimatedNumber.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFEFloodElement_element_string;
}

namespace svg {
	class SVGFEFloodElement :
		public SVGElement,
		public SVGStylable,
		public SVGFilterPrimitiveStandardAttributes {
	public:
	protected:
		Attribute< SVGAnimatedString > in1;
		Attribute< SVGAnimatedString > floodColor;
		Attribute< SVGAnimatedNumber > floodOpacity;
	public:
		const Attribute< SVGAnimatedString >& dom_getIn1() const { return in1; }

		const Attribute< SVGAnimatedString >& dom_getFloodColor() const { return floodColor; }

		const Attribute< SVGAnimatedNumber >& dom_getFloodOpacity() const { return floodOpacity; }

	public:
		const SVGString & getIn1() const { return in1.getValue().getAnimatedVal().getValue(); }
		void setIn1(const SVGString& n)  { in1.getValue().getAnimatedVal().setValue(n); in1.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGString & getFloodColor() const { return floodColor.getValue().getAnimatedVal().getValue(); }
		void setFloodColor(const SVGString& n)  { floodColor.getValue().getAnimatedVal().setValue(n); floodColor.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGNumber & getFloodOpacity() const { return floodOpacity.getValue().getAnimatedVal().getValue(); }
		void setFloodOpacity(const SVGNumber& n)  { floodOpacity.getValue().getAnimatedVal().setValue(n); floodOpacity.getValue().getBaseVal().setValue(n);  setDamaged(true); }


		virtual void glPreTraverse(svgl::Context*, svgl::GLInfo*, SVGElement* elem, svgl::FilterContext*)  ;
		virtual void glPostTraverse(svgl::Context*, svgl::GLInfo*, SVGElement* elem, svgl::FilterContext*)  ;
		virtual unicode::String* getOptionalIn1();
		virtual unicode::String* getOptionalIn2();
		virtual unicode::String* getOptionalResult();

	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFEFloodElement();
		virtual const String getDtdElement() const { return SVGFEFloodElement_element_string; }
		SVGFEFloodElement(dom::Document* doc) : SVGElement(doc, SVGFEFloodElement_element_string) {}
	};
}


#endif // __svg_SVGFEFloodElement__
