#ifndef __svg_SVGFEImageElement__
#define __svg_SVGFEImageElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGURIReference.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGTransformable.hpp>
#include <w3c/svg/SVGFilterPrimitiveStandardAttributes.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFEImageElement_element_string;
}

namespace svg {
	class SVGFEImageElement :
		public SVGElement,
		public SVGURIReference,
		public SVGLangSpace,
		public SVGExternalResourcesRequired,
		public SVGStylable,
		public SVGTransformable,
		public SVGFilterPrimitiveStandardAttributes {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFEImageElement();
		virtual const String getDtdElement() const { return SVGFEImageElement_element_string; }
		SVGFEImageElement(dom::Document* doc) : SVGElement(doc, SVGFEImageElement_element_string) {}
	};
}


#endif // __svg_SVGFEImageElement__
