#ifndef __svg_SVGFontElement__
#define __svg_SVGFontElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFontElement_element_string;
}

namespace svg {
	class SVGFontElement :
		public SVGElement,
		public SVGExternalResourcesRequired,
		public SVGStylable {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFontElement();
		virtual const String getDtdElement() const { return SVGFontElement_element_string; }
		SVGFontElement(dom::Document* doc) : SVGElement(doc, SVGFontElement_element_string) {}
	};
}


#endif // __svg_SVGFontElement__
