#ifndef __svg_SVGFontFaceElement__
#define __svg_SVGFontFaceElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGFontFaceElement_element_string;
}

namespace svg {
	class SVGFontFaceElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGFontFaceElement();
		virtual const String getDtdElement() const { return SVGFontFaceElement_element_string; }
		SVGFontFaceElement(dom::Document* doc) : SVGElement(doc, SVGFontFaceElement_element_string) {}
	};
}


#endif // __svg_SVGFontFaceElement__
