#ifndef __svg_SVGGElement__
#define __svg_SVGGElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
	class Context;
	class GLInfo;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGTests.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGTransformable.hpp>
#include <w3c/events/EventTarget.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGGElement_element_string;
}

namespace svg {
	class SVGGElement :
		public SVGElement,
		public SVGTests,
		public SVGLangSpace,
		public SVGExternalResourcesRequired,
		public SVGStylable,
		public SVGTransformable,
		public events::EventTarget {
	public:

		virtual void glTraverse(svgl::Context*, svgl::GLInfo*)  ;

		virtual void glTraverseBranch(svgl::Context*, svgl::GLInfo*, Branch::iterator& beg, Branch::iterator& end)   ;

		virtual void pickTraverse(svgl::Context*, svgl::GLInfo*)  ;
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGGElement();
		virtual const String getDtdElement() const { return SVGGElement_element_string; }
		SVGGElement(dom::Document* doc) : SVGElement(doc, SVGGElement_element_string) {}
	};
}


#endif // __svg_SVGGElement__
