#ifndef __svg_SVGHKernElement__
#define __svg_SVGHKernElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGHKernElement_element_string;
}

namespace svg {
	class SVGHKernElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGHKernElement();
		virtual const String getDtdElement() const { return SVGHKernElement_element_string; }
		SVGHKernElement(dom::Document* doc) : SVGElement(doc, SVGHKernElement_element_string) {}
	};
}


#endif // __svg_SVGHKernElement__
