#ifndef __svg_SVGICCColor__
#define __svg_SVGICCColor__

// generated by genFromIdl.py

namespace svg {
}

#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/DOMString.hpp>
#include <w3c/svg/SVGNumberList.hpp>

namespace svg {
	class SVGICCColor {
	public:
	protected:
		Attribute< DOMString > colorProfile;
		Attribute< SVGNumberList > colors;
	public:
		const Attribute< DOMString >& dom_getColorProfile() const { return colorProfile; }
		Attribute< DOMString >& dom_getColorProfile() { return colorProfile; }
		void dom_setColorProfile(const DOMString& n)  { colorProfile.setValue(n); }

		const Attribute< SVGNumberList >& dom_getColors() const { return colors; }

	public:
		const DOMString & getColorProfile() const { return colorProfile.getValue(); }
		DOMString & getColorProfile() { return colorProfile.getValue(); }
		void setColorProfile(const DOMString& n)  { colorProfile.setValue(n); }

		const SVGNumberList & getColors() const { return colors.getValue(); }
		void setColors(const SVGNumberList& n)  { colors.setValue(n); }

	public:

	public:
		virtual ~SVGICCColor();
	};
}


#endif // __svg_SVGICCColor__
