#ifndef __svg_SVGLocatable__
#define __svg_SVGLocatable__

// generated by genFromIdl.py

namespace svg {
	class SVGElement;
	class SVGElement;
	class SVGRect;
	class SVGMatrix;
}

#include <w3c/svg/Attribute.hpp>

namespace svg {
	class SVGLocatable {
	public:
	protected:
		Attribute< SVGElement* > nearestViewportElement;
		Attribute< SVGElement* > farthestViewportElement;
	public:
		const Attribute< SVGElement* >& dom_getNearestViewportElement() const { return nearestViewportElement; }

		const Attribute< SVGElement* >& dom_getFarthestViewportElement() const { return farthestViewportElement; }

	public:
		const SVGElement* getNearestViewportElement() const { return nearestViewportElement.getValue(); }
		void setNearestViewportElement(SVGElement* n)  { nearestViewportElement.setValue(n); }

		const SVGElement* getFarthestViewportElement() const { return farthestViewportElement.getValue(); }
		void setFarthestViewportElement(SVGElement* n)  { farthestViewportElement.setValue(n); }

	public:
		virtual SVGRect* getBBox (  ) ;
		virtual SVGMatrix* getCTM (  ) ;
		virtual SVGMatrix* getScreenCTM (  ) ;
		virtual SVGMatrix* getTransformToElement ( const SVGElement& element ) ;

	public:
		virtual ~SVGLocatable();
	};
}


#endif // __svg_SVGLocatable__
