// generated by makeList.py
#ifndef __svg_LengthList__
#define __svg_LengthList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGLength.hpp>

namespace svg {
   typedef SVGList<SVGLength> SVGLengthList;
}

#endif // __svg_LengthList__
