#ifndef __svg_SVGMPathElement__
#define __svg_SVGMPathElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/DOMString.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGMPathElement_element_string;
}

namespace svg {
	class SVGMPathElement :
		public SVGElement {
	public:
	protected:
		Attribute< DOMString > href;
	public:
		const Attribute< DOMString >& dom_getHref() const { return href; }

	public:
		const DOMString & getHref() const { return href.getValue(); }
		void setHref(const DOMString& n)  { href.setValue(n);  setDamaged(true); }

	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGMPathElement();
		virtual const String getDtdElement() const { return SVGMPathElement_element_string; }
		SVGMPathElement(dom::Document* doc) : SVGElement(doc, SVGMPathElement_element_string) {}
	};
}


#endif // __svg_SVGMPathElement__
