#ifndef __svg_SVGMissingGlyphElement__
#define __svg_SVGMissingGlyphElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGMissingGlyphElement_element_string;
}

namespace svg {
	class SVGMissingGlyphElement :
		public SVGElement,
		public SVGStylable {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGMissingGlyphElement();
		virtual const String getDtdElement() const { return SVGMissingGlyphElement_element_string; }
		SVGMissingGlyphElement(dom::Document* doc) : SVGElement(doc, SVGMissingGlyphElement_element_string) {}
	};
}


#endif // __svg_SVGMissingGlyphElement__
