#ifndef __svg_SVGMetadataElement__
#define __svg_SVGMetadataElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGMetadataElement_element_string;
}

namespace svg {
	class SVGMetadataElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGMetadataElement();
		virtual const String getDtdElement() const { return SVGMetadataElement_element_string; }
		SVGMetadataElement(dom::Document* doc) : SVGElement(doc, SVGMetadataElement_element_string) {}
	};
}


#endif // __svg_SVGMetadataElement__
