#ifndef __svg_SVGNumber__
#define __svg_SVGNumber__

// generated by genFromIdl.py

namespace svg {
}

#include <w3c/svg/Attribute.hpp>

namespace svg {
	class SVGNumber {
	public:
	protected:
		Attribute< float > value;
	public:
		const Attribute< float >& dom_getValue() const { return value; }
		Attribute< float >& dom_getValue() { return value; }
		void dom_setValue(const float& n)  { value.setValue(n); }

	public:
		const float & getValue() const { return value.getValue(); }
		float & getValue() { return value.getValue(); }
		void setValue(const float& n)  { value.setValue(n); }

	public:

	public:
		virtual ~SVGNumber();
	};
}


#endif // __svg_SVGNumber__
