// generated by makeList.py
#ifndef __svg_NumberList__
#define __svg_NumberList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGNumber.hpp>

namespace svg {
   typedef SVGList<SVGNumber> SVGNumberList;
}

#endif // __svg_NumberList__
