#ifndef __svg_SVGPoint__
#define __svg_SVGPoint__

// generated by genFromIdl.py

namespace svg {
	class SVGPoint;
	class SVGMatrix;
}

#include <w3c/svg/Attribute.hpp>

namespace svg {
	class SVGPoint {
	public:
	protected:
		Attribute< float > x;
		Attribute< float > y;
	public:
		const Attribute< float >& dom_getX() const { return x; }
		Attribute< float >& dom_getX() { return x; }
		void dom_setX(const float& n)  { x.setValue(n); }

		const Attribute< float >& dom_getY() const { return y; }
		Attribute< float >& dom_getY() { return y; }
		void dom_setY(const float& n)  { y.setValue(n); }

	public:
		const float & getX() const { return x.getValue(); }
		float & getX() { return x.getValue(); }
		void setX(const float& n)  { x.setValue(n); }

		const float & getY() const { return y.getValue(); }
		float & getY() { return y.getValue(); }
		void setY(const float& n)  { y.setValue(n); }

	public:
		virtual SVGPoint* matrixTransform ( const SVGMatrix& matrix ) ;

	public:
		virtual ~SVGPoint();
	};
}


#endif // __svg_SVGPoint__
