// generated by makeList.py
#ifndef __svg_PointList__
#define __svg_PointList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGPoint.hpp>

namespace svg {
   typedef SVGList<SVGPoint> SVGPointList;
}

#endif // __svg_PointList__
