// generated by makeList.py
#ifndef __svg_PathSegList__
#define __svg_PathSegList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGPathSeg.hpp>

namespace svg {
   typedef SVGList<SVGPathSeg*> SVGPathSegList;
}

#endif // __svg_PathSegList__
