#ifndef __svg_SVGPathSegLinetoVerticalRel__
#define __svg_SVGPathSegLinetoVerticalRel__

// generated by genFromIdl.py
	class BezierPath;

namespace svg {
}

namespace agg {
	class path_storage;
}

#include <w3c/svg/SVGPathSeg.hpp>
#include <w3c/svg/Attribute.hpp>

namespace svg {
	class SVGPathSegLinetoVerticalRel :
		public SVGPathSeg {
	public:
	protected:
		Attribute< float > y;
	public:
		const Attribute< float >& dom_getY() const { return y; }
		Attribute< float >& dom_getY() { return y; }
		void dom_setY(const float& n)  { y.setValue(n); }

	public:
		const float & getY() const { return y.getValue(); }
		float & getY() { return y.getValue(); }
		void setY(const float& n)  { y.setValue(n); }


	public:
		SVGPathSegLinetoVerticalRel() : SVGPathSeg(PATHSEG_LINETO_VERTICAL_REL,'v') {}
		virtual ~SVGPathSegLinetoVerticalRel() {}
		virtual void updateBezier(BezierPath&) const;
		virtual void updateBezier(agg::path_storage&) const;
	public:
	};
}


#endif // __svg_SVGPathSegLinetoVerticalRel__
