#ifndef __svg_SVGRenderingIntent__
#define __svg_SVGRenderingIntent__

// generated by genFromIdl.py

namespace svg {
}


namespace svg {
	class SVGRenderingIntent {
	public:

		enum RENDERING_INTENT {
			RENDERING_INTENT_UNKNOWN = 0,
			RENDERING_INTENT_AUTO = 1,
			RENDERING_INTENT_PERCEPTUAL = 2,
			RENDERING_INTENT_RELATIVE_COLORIMETRIC = 3,
			RENDERING_INTENT_SATURATION = 4,
			RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 5
		};

	public:

	public:
		virtual ~SVGRenderingIntent();
	};
}


#endif // __svg_SVGRenderingIntent__
