#ifndef __svg_SVGSetElement__
#define __svg_SVGSetElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGAnimationElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGSetElement_element_string;
}

namespace svg {
	class SVGSetElement :
		public SVGAnimationElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGSetElement();
		virtual const String getDtdElement() const { return SVGSetElement_element_string; }
		SVGSetElement(dom::Document* doc) : SVGAnimationElement(doc, SVGSetElement_element_string) {}
	};
}


#endif // __svg_SVGSetElement__
