#ifndef __svg_SVGSymbolElement__
#define __svg_SVGSymbolElement__

// generated by genFromIdl.py
	class xmlostream;
	class DOM_Node;

namespace svg {
	class SVGSVGElement;
}

namespace svgl {
	class AnimateAdapter;
	class Context;
	class GLInfo;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGFitToViewBox.hpp>
#include <w3c/events/EventTarget.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGSymbolElement_element_string;
}

namespace svg {
	class SVGSymbolElement :
		public SVGElement,
		public SVGLangSpace,
		public SVGExternalResourcesRequired,
		public SVGStylable,
		public SVGFitToViewBox,
		public events::EventTarget {
	public:

public:
		void setOwnerAndViewPort(SVGSVGElement* owner, SVGElement* viewport);
	public:
		void glTraverseFromUse(svgl::Context*, svgl::GLInfo* glinfo, float width, float height);
		void pickTraverseFromUse(svgl::Context*, svgl::GLInfo* glinfo, float width, float height);

		virtual void glTraverse(svgl::Context*, svgl::GLInfo*)  ;

		virtual void pickTraverse(svgl::Context*, svgl::GLInfo*)  ;
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGSymbolElement();
		virtual const String getDtdElement() const { return SVGSymbolElement_element_string; }
		SVGSymbolElement(dom::Document* doc) : SVGElement(doc, SVGSymbolElement_element_string) {}
	};
}


#endif // __svg_SVGSymbolElement__
