// generated by makeList.py
#ifndef __svg_StringList__
#define __svg_StringList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGString.hpp>

namespace svg {
   typedef SVGList<SVGString> SVGStringList;
}

#endif // __svg_StringList__
