#ifndef __svg_SVGSwitchElement__
#define __svg_SVGSwitchElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGTests.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGTransformable.hpp>
#include <w3c/events/EventTarget.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGSwitchElement_element_string;
}

namespace svg {
	class SVGSwitchElement :
		public SVGElement,
		public SVGTests,
		public SVGLangSpace,
		public SVGExternalResourcesRequired,
		public SVGStylable,
		public SVGTransformable,
		public events::EventTarget {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGSwitchElement();
		virtual const String getDtdElement() const { return SVGSwitchElement_element_string; }
		SVGSwitchElement(dom::Document* doc) : SVGElement(doc, SVGSwitchElement_element_string) {}
	};
}


#endif // __svg_SVGSwitchElement__
