// generated by makeList.py
#ifndef __svg_TransformList__
#define __svg_TransformList__

#include <w3c/svg/SVGList.hpp>
#include <w3c/svg/SVGTransform.hpp>

namespace svg {
   typedef SVGList<SVGTransform*> SVGTransformList;
}

#endif // __svg_TransformList__
