#ifndef __svg_SVGUnitTypes__
#define __svg_SVGUnitTypes__

// generated by genFromIdl.py

namespace svg {
}


namespace svg {
	class SVGUnitTypes {
	public:

		enum SVG_UNIT_TYPE {
			SVG_UNIT_TYPE_UNKNOWN = 0,
			SVG_UNIT_TYPE_USERSPACEONUSE = 1,
			SVG_UNIT_TYPE_OBJECTBOUNDINGBOX = 2
		};

	public:

	public:
		virtual ~SVGUnitTypes();
	};
}


#endif // __svg_SVGUnitTypes__
