#ifndef __svg_SVGUseElement__
#define __svg_SVGUseElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
	class SVGElementInstance;
	class SVGElementInstance;
}

namespace svgl {
	class AnimateAdapter;
	class Context;
	class GLInfo;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/SVGURIReference.hpp>
#include <w3c/svg/SVGTests.hpp>
#include <w3c/svg/SVGLangSpace.hpp>
#include <w3c/svg/SVGExternalResourcesRequired.hpp>
#include <w3c/svg/SVGStylable.hpp>
#include <w3c/svg/SVGTransformable.hpp>
#include <w3c/events/EventTarget.hpp>
#include <w3c/svg/Attribute.hpp>
#include <w3c/svg/SVGAnimatedLength.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGUseElement_element_string;
}

namespace svg {
	class SVGUseElement :
		public SVGElement,
		public SVGURIReference,
		public SVGTests,
		public SVGLangSpace,
		public SVGExternalResourcesRequired,
		public SVGStylable,
		public SVGTransformable,
		public events::EventTarget {
	public:
	protected:
		Attribute< SVGAnimatedLength > x;
		Attribute< SVGAnimatedLength > y;
		Attribute< SVGAnimatedLength > width;
		Attribute< SVGAnimatedLength > height;
		Attribute< SVGElementInstance* > instanceRoot;
		Attribute< SVGElementInstance* > animatedInstanceRoot;
	public:
		const Attribute< SVGAnimatedLength >& dom_getX() const { return x; }

		const Attribute< SVGAnimatedLength >& dom_getY() const { return y; }

		const Attribute< SVGAnimatedLength >& dom_getWidth() const { return width; }

		const Attribute< SVGAnimatedLength >& dom_getHeight() const { return height; }

		const Attribute< SVGElementInstance* >& dom_getInstanceRoot() const { return instanceRoot; }

		const Attribute< SVGElementInstance* >& dom_getAnimatedInstanceRoot() const { return animatedInstanceRoot; }

	public:
		const SVGLength & getX() const { return x.getValue().getAnimatedVal().getValue(); }
		void setX(const SVGLength& n)  { x.getValue().getAnimatedVal().setValue(n); x.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGLength & getY() const { return y.getValue().getAnimatedVal().getValue(); }
		void setY(const SVGLength& n)  { y.getValue().getAnimatedVal().setValue(n); y.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGLength & getWidth() const { return width.getValue().getAnimatedVal().getValue(); }
		void setWidth(const SVGLength& n)  { width.getValue().getAnimatedVal().setValue(n); width.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGLength & getHeight() const { return height.getValue().getAnimatedVal().getValue(); }
		void setHeight(const SVGLength& n)  { height.getValue().getAnimatedVal().setValue(n); height.getValue().getBaseVal().setValue(n);  setDamaged(true); }

		const SVGElementInstance* getInstanceRoot() const { return instanceRoot.getValue(); }
		void setInstanceRoot(SVGElementInstance* n)  { instanceRoot.setValue(n);  setDamaged(true); }

		const SVGElementInstance* getAnimatedInstanceRoot() const { return animatedInstanceRoot.getValue(); }
		void setAnimatedInstanceRoot(SVGElementInstance* n)  { animatedInstanceRoot.setValue(n);  setDamaged(true); }


	public:
	virtual void registerUse(svgl::Context*);
	virtual bool areChildrenDamaged();
        virtual void damageChildren();

		virtual void glTraverse(svgl::Context*, svgl::GLInfo*)  ;

		virtual void glTraverseBoundingBox(svgl::Context*, svgl::GLInfo*)  ;

		virtual void pickTraverse(svgl::Context*, svgl::GLInfo*)  ;
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGUseElement();
		virtual const String getDtdElement() const { return SVGUseElement_element_string; }
		SVGUseElement(dom::Document* doc) : SVGElement(doc, SVGUseElement_element_string) {}
	};
}


#endif // __svg_SVGUseElement__
