#ifndef __svg_SVGVKernElement__
#define __svg_SVGVKernElement__

// generated by genFromIdl.py
	class xmlostream;

namespace svg {
}

namespace svgl {
	class AnimateAdapter;
}

#include <w3c/svg/SVGElement.hpp>
#include <w3c/svg/String.hpp>

namespace svg {
            extern unicode::String * SVGVKernElement_element_string;
}

namespace svg {
	class SVGVKernElement :
		public SVGElement {
	public:
	public:
		virtual int parse_attributes(const String&, const String&);
		virtual void print_attributes(xmlostream&);
	public:
		virtual svgl::AnimateAdapter* getAttributeByName(const String&);

	public:
		virtual ~SVGVKernElement();
		virtual const String getDtdElement() const { return SVGVKernElement_element_string; }
		SVGVKernElement(dom::Document* doc) : SVGElement(doc, SVGVKernElement_element_string) {}
	};
}


#endif // __svg_SVGVKernElement__
